name: WerewolfGame
version: @version@
main: jp.hack.minecraft.werewolfgame.Main
api-version: 1.12
commands:
  werewolf:
    aliases: ww
    description: main command
    usage: "Usage: /<command>"
    permission: werewolf.admin
    permission-message: You dont't have <permission>
permissions:
    werewolf.admin:
    description: game master permission
    default: op